#ifndef OCONVEXHULL2D_H__
#define OCONVEXHULL2D_H__

enum
{
	CONVEXHULL2D_PRECISION = 1000,
	GEOMETRYBASED,	
	BOUNDINGPLANE,
	TEXT_DUMMY,
	EXPANSION_FLOAT,

	EXPANSION_MODE,
	EXPANSION_MODE_TANGENT,
	
	//Parameter controls
	//Generally keep these from id 1100 onwards
	INTERSECTION_PLANE_TARGET = 1100,
};

#endif // OCONVEXHULL2D_H__
